DirectoryPath ROOT_PATH = MakeAbsolute(Directory("../.."));
DirectoryPath OUTPUT_PATH = MakeAbsolute(ROOT_PATH.Combine("output/native"));

#load "../../scripts/cake/native-shared.cake"

string SUPPORT_GPU_VAR = Argument("supportGpu", EnvironmentVariable("SUPPORT_GPU") ?? "true").ToLower();
string EMSCRIPTEN_ROOT = Argument("emscripten", EnvironmentVariable("EMSCRIPTEN_SDK_ROOT") ?? EnvironmentVariable("EMSDK") ?? "");
string EMSCRIPTEN_VERSION = Argument("emscriptenVersion", EnvironmentVariable("EMSCRIPTEN_VERSION") ?? "").ToLower();
string[] EMSCRIPTEN_FEATURES = Argument("emscriptenFeatures", EnvironmentVariable("EMSCRIPTEN_FEATURES") ?? "").ToLower()
    .Split(",").Where(f => f != "none").ToArray();
bool SUPPORT_GPU = SUPPORT_GPU_VAR == "1" || SUPPORT_GPU_VAR == "true";

// Shared by the 'libSkiaSharp' and 'generate-wasm-symbol-renames' tasks, so the symbol discovery
// build always matches the exact feature set of the build it renames symbols for.
bool HAS_SIMD_ENABLED = EMSCRIPTEN_FEATURES.Contains("simd") || EMSCRIPTEN_FEATURES.Contains("_simd");
bool HAS_THREADING_ENABLED = EMSCRIPTEN_FEATURES.Contains("mt");
bool HAS_WASM_EH = EMSCRIPTEN_FEATURES.Contains("_wasmeh");

// Off by default: renaming is only useful (and only verified) when this static library ends up
// statically linked alongside a host application's own copies of freetype2/libjpeg-turbo/
// libpng (eg. a Unity build). Leaving this off keeps the default wasm build exactly as it was
// before.
string SYMBOL_RENAMES_VAR = Argument("wasmRenameThirdPartySymbols", EnvironmentVariable("WASM_RENAME_THIRDPARTY_SYMBOLS") ?? "false").ToLower();
bool ENABLE_SYMBOL_RENAMES = SYMBOL_RENAMES_VAR == "1" || SYMBOL_RENAMES_VAR == "true";

string CC = Argument("cc", "emcc");
string CXX = Argument("cxx", "em++");
string AR = Argument("ar", "emar");
string NM = Argument("nm", "emnm");
string COMPILERS = $"cc='{CC}' cxx='{CXX}' ar='{AR}' ";

// Symbols that freetype2/libjpeg-turbo/libpng would otherwise export as globals (eg. FT_*,
// jpeg_*, png_*, and their non-static internal helpers) get renamed with this
// prefix when ENABLE_SYMBOL_RENAMES is on, so this static library cannot collide with a host
// application's own copies of the same libraries when both are statically linked together.
// The header below is regenerated by the 'generate-wasm-symbol-renames' task as a dependency of
// every build that enables renaming (see 'libSkiaSharp' below), using that same build's checkout
// and GN args, so it cannot go stale relative to the freetype2/libjpeg-turbo/libpng checkout
// or the SIMD/threading/exception-handling flags actually being built.
string SYMBOL_RENAME_PREFIX = "sksharp_";
FilePath SYMBOL_RENAMES_HEADER = MakeAbsolute(ROOT_PATH.CombineWithFilePath("native/wasm/libSkiaSharp/wasm_symbol_renames.h"));

// HarfBuzz's own public hb_* API is renamed the same way (see 'generate-wasm-harfbuzz-symbol-
// renames' below) -- but unlike freetype2/libjpeg-turbo/zlib/libpng, that API is also what the managed
// HarfBuzzSharp binding P/Invokes directly, so the renamed names need aliasing back. See
// documentation/wasm-symbol-renaming.md for the full rationale.
FilePath HARFBUZZ_SYMBOL_RENAMES_HEADER = MakeAbsolute(ROOT_PATH.CombineWithFilePath("native/wasm/libHarfBuzzSharp/wasm_symbol_renames.h"));
FilePath HARFBUZZ_HB_EXTERN_VISIBILITY_HEADER = MakeAbsolute(ROOT_PATH.CombineWithFilePath("native/wasm/libHarfBuzzSharp/wasm_hb_extern_visibility.h"));
// Force-included, not a separately-compiled source file: __attribute__((alias(...))) requires its
// target defined in the *same* translation unit, which harfbuzz-subset.cc's single-TU amalgamation
// provides -- see the -include order in HarfBuzzSharpGnArgs below.
FilePath HARFBUZZ_SYMBOL_ALIASES_HEADER = MakeAbsolute(ROOT_PATH.CombineWithFilePath("native/wasm/libHarfBuzzSharp/wasm_symbol_aliases.h"));

string WasmSkiaGnArgs(bool hasSimdEnabled, bool hasThreadingEnabled, bool hasWasmEH, bool includeSymbolRenames)
{
    return
        $"target_os='linux' " +
        $"target_cpu='wasm' " +
        $"is_static_skiasharp=true " +
        $"skia_enable_fontmgr_custom_directory=false " +
        $"skia_enable_fontmgr_custom_empty=false " +
        $"skia_enable_fontmgr_custom_embedded=true " +
        $"skia_enable_fontmgr_empty=false " +
        $"skia_enable_ganesh={(SUPPORT_GPU ? "true" : "false")} " +
        (SUPPORT_GPU ? "skia_gl_standard='webgl'" : "") +
        $"skia_enable_pdf=true " +
        $"skia_use_dng_sdk=false " +
        $"skia_use_webgl=true " +
        $"skia_use_fontconfig=false " +
        $"skia_use_freetype=true " +
        $"skia_use_harfbuzz=false " +
        $"skia_use_icu=false " +
        $"skia_use_piex=false " +
        $"skia_use_sfntly=false " +
        $"skia_use_expat=true " +
        $"skia_use_libwebp_encode=true " +
        $"skia_use_system_expat=false " +
        $"skia_use_system_freetype2=false " +
        $"skia_use_system_libjpeg_turbo=false " +
        $"skia_use_system_libpng=false " +
        $"skia_use_system_libwebp=false " +
        $"skia_use_system_zlib=false " +
        $"skia_use_vulkan=false " +
        $"skia_use_wuffs=true " +
        $"skia_enable_skottie=true " +
        $"use_PIC=false " +
        $"extra_cflags=[ " +
        $"  '-DSKIA_C_DLL', '-DXML_POOR_ENTROPY', " +
        $" {(!hasSimdEnabled ? "'-DSKNX_NO_SIMD', " : "")} '-DSK_DISABLE_AAA', '-DGR_GL_CHECK_ALLOC_WITH_GET_ERROR=0', " +
        $"  '-s', 'WARN_UNALIGNED=1' " + // '-s', 'USE_WEBGL2=1' (experimental)
        $"  { (hasSimdEnabled ? ", '-msimd128'" : "") } " +
        $"  { (hasThreadingEnabled ? ", '-pthread'" : "") } " +
        $"  { (hasWasmEH ? ", '-fwasm-exceptions'" : "") } " +
        // libpng's own PNG_USE_READ_MACROS optimization redefines png_get_uint_16/uint_32/int_32
        // as function-like macros later in the same translation unit (png.h), which silently wins
        // over our plain #define rename for just these three symbols -- disable it so the rename
        // applies uniformly like it does to every other libpng/freetype2/libjpeg-turbo symbol.
        $"  { (includeSymbolRenames ? ", '-DPNG_NO_USE_READ_MACROS'" : "") } " +
        $"  { (includeSymbolRenames ? $", '-include', '{SYMBOL_RENAMES_HEADER.FullPath}'" : "") } " +
        $"] " +
        // SIMD support is based on https://github.com/google/skia/blob/1f193df9b393d50da39570dab77a0bb5d28ec8ef/modules/canvaskit/compile.sh#L57
        $"extra_cflags_cc=[ '-frtti' { (hasSimdEnabled ? ", '-msimd128'" : "") } { (hasThreadingEnabled ? ", '-pthread'" : "") } { (hasWasmEH ? ", '-fwasm-exceptions'" : "") } ] " +
        $"skia_emsdk_dir='{EMSCRIPTEN_ROOT}'" +
        COMPILERS +
        ADDITIONAL_GN_ARGS;
}

// harfbuzz needs a heavier mechanism than freetype2/libjpeg-turbo/libpng above: it's mostly C++-mangled
// (textual #define renaming can't reach mangled names), and its public hb_* API is also SkiaSharp.HarfBuzz's P/Invoke surface.
// The fix combines '-fvisibility=hidden' (hides internals),
// HARFBUZZ_HB_EXTERN_VISIBILITY_HEADER (keeps the public API exported despite that),
// and HARFBUZZ_SYMBOL_RENAMES_HEADER + HARFBUZZ_SYMBOL_ALIASES_HEADER (renames the public API, then aliases the P/Invoke'd subset back to its original name).
// See documentation/wasm-symbol-renaming.md for the full picture.
string HarfBuzzSharpGnArgs(bool hasSimdEnabled, bool hasThreadingEnabled, bool hasWasmEH, bool hideInternalSymbols, bool includeGeneratedRenames)
{
    return
        $"target_os='linux' " +
        $"target_cpu='wasm' " +
        $"is_static_skiasharp=true " +
        $"visibility_hidden={(hideInternalSymbols ? "true" : "false")} " +
        $"extra_cflags=[ '-s', 'WARN_UNALIGNED=1' " +
        $"  { (hasSimdEnabled ? ", '-msimd128'" : "") } " +
        $"  { (hasThreadingEnabled ? ", '-pthread'" : "") } " +
        $"  { (hasWasmEH ? ", '-fwasm-exceptions'" : "") } " +
        $"  { (hideInternalSymbols ? $", '-include', '{HARFBUZZ_HB_EXTERN_VISIBILITY_HEADER.FullPath}'" : "") } " +
        // Order matters: the alias declarations must be force-included *before* the renames
        // header, while 'hb_x' still means literally 'hb_x' -- otherwise the renames header's
        // '#define hb_x sksharp_hb_x' would also rewrite these declarations' own names.
        $"  { (includeGeneratedRenames ? $", '-include', '{HARFBUZZ_SYMBOL_ALIASES_HEADER.FullPath}'" : "") } " +
        $"  { (includeGeneratedRenames ? $", '-include', '{HARFBUZZ_SYMBOL_RENAMES_HEADER.FullPath}'" : "") } " +
        $"] " +
        $"extra_cflags_cc=[ '-frtti' { (hasSimdEnabled ? ", '-msimd128'" : "") } { (hasThreadingEnabled ? ", '-pthread'" : "") } { (hasWasmEH ? ", '-fwasm-exceptions'" : "") } ] " +
        $"skia_emsdk_dir='{EMSCRIPTEN_ROOT}'" +
        COMPILERS +
        ADDITIONAL_GN_ARGS;
}

// The harfbuzz function names the managed HarfBuzzSharp binding P/Invokes directly (eg.
// 'hb_blob_create') -- derived from the DllImport/LibraryImport declarations themselves (not
// hand-maintained), so it always matches whatever the binding actually calls. Used to decide
// which renamed harfbuzz symbols need an alias back to their original name.
SortedSet<string> GetHarfBuzzManagedApiNames()
{
    var files = new[] {
        ROOT_PATH.CombineWithFilePath("binding/HarfBuzzSharp/HarfBuzzApi.cs"),
        ROOT_PATH.CombineWithFilePath("binding/HarfBuzzSharp/HarfBuzzApi.generated.cs"),
    };
    // Matches a bare 'hb_...' identifier immediately followed by '(' -- covers DllImport/
    // LibraryImport extern declarations, the USE_DELEGATES delegate type declarations, and (
    // harmlessly, since it is the same name) the '// extern ...' doc comment above each one.
    // Excludes '// typedef hb_bool_t (*)(...)'-style function-pointer doc comments, whose
    // '(' belongs to the pointer syntax, not a call -- those would otherwise wrongly pick up
    // the *return type* (eg. 'hb_bool_t') as if it were a function name.
    var regex = new System.Text.RegularExpressions.Regex(@"\bhb_[A-Za-z0-9_]*\b(?=\s*\()");
    var names = new SortedSet<string>();
    foreach (var file in files) {
        foreach (var line in System.IO.File.ReadAllLines(file.FullPath)) {
            if (line.TrimStart().StartsWith("// typedef"))
                continue;
            foreach (System.Text.RegularExpressions.Match m in regex.Matches(line))
                names.Add(m.Value);
        }
    }
    return names;
}

// harfbuzz sometimes wraps a definition's name in parens (eg. '(hb_color_get_alpha) (...)') to
// stop its own inline function-like macro from firing at the definition site -- but that also
// defeats our rename macro there, producing a renamed prototype but an unrenamed definition that
// fails to compile under -Wmissing-prototypes. Detected generically by scanning harfbuzz's own
// sources for that idiom; names found here are simply left out of the rename table (both sides
// then agree on the real name). See documentation/wasm-symbol-renaming.md for the full story.
SortedSet<string> GetHarfBuzzMacroShadowedNames()
{
    var regex = new System.Text.RegularExpressions.Regex(@"^\((hb_[A-Za-z0-9_]+)\)\s*\(", System.Text.RegularExpressions.RegexOptions.Multiline);
    var names = new SortedSet<string>();
    var srcDir = SKIA_PATH.Combine("third_party/externals/harfbuzz/src");
    var files = GetFiles($"{srcDir}/*.cc").Concat(GetFiles($"{srcDir}/*.h")).Concat(GetFiles($"{srcDir}/*.hh"));
    foreach (var file in files) {
        var text = System.IO.File.ReadAllText(file.FullPath);
        foreach (System.Text.RegularExpressions.Match m in regex.Matches(text))
            names.Add(m.Groups[1].Value);
    }
    return names;
}

// Reads an archive's global, defined symbols -- ie. the ones that would participate in a
// "duplicate symbol" collision if a host application statically links its own copy of the same
// library alongside this one.
HashSet<string> GetDefinedGlobalSymbols(FilePath archive)
{
    RunProcess(NM, $"--defined-only --extern-only \"{archive.FullPath}\"", out IEnumerable<string> stdout);

    var symbols = new HashSet<string>();
    foreach (var line in stdout) {
        // eg. "0000000000000010 T FT_Init_FreeType" -- archive member header lines don't match.
        var parts = line.Trim().Split((char[])null, StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 3 && parts[1].Length == 1 && System.Text.RegularExpressions.Regex.IsMatch(parts[0], "^[0-9a-fA-F]+$"))
            symbols.Add(parts[2]);
    }
    return symbols;
}

// Finds which .a in outDir defines anchorSymbol, without assuming what GN names the output file
// for a given target (the third_party() GN template doesn't guarantee it).
FilePath FindArchiveContaining(DirectoryPath outDir, string anchorSymbol)
{
    FilePath found = null;
    foreach (var file in GetFiles($"{outDir}/*.a")) {
        if (GetDefinedGlobalSymbols(file).Contains(anchorSymbol)) {
            if (found != null)
                throw new Exception($"Symbol '{anchorSymbol}' was found in both '{found}' and '{file}' -- cannot uniquely identify the archive.");
            found = file;
        }
    }
    if (found == null)
        throw new Exception($"Could not find an archive defining '{anchorSymbol}' under '{outDir}' -- did the discovery build succeed?");
    return found;
}

// Builds freetype2, libjpeg-turbo and libpng in isolation (a dedicated out dir, so the
// normal 'libSkiaSharp' build/output is untouched) and records every global symbol they define,
// so 'libSkiaSharp' can rename all of them and avoid colliding with a host application's own
// copies of the same libraries. Runs automatically as a dependency of 'libSkiaSharp' whenever
// --wasmRenameThirdPartySymbols is enabled (skipped otherwise), using that build's own checkout
// and GN args, so the discovered symbols always match what is actually being built.
Task("generate-wasm-symbol-renames")
    .IsDependentOn("git-sync-deps")
    .WithCriteria(IsRunningOnLinux() && ENABLE_SYMBOL_RENAMES)
    .Does(() =>
{
    var args = WasmSkiaGnArgs(HAS_SIMD_ENABLED, HAS_THREADING_ENABLED, HAS_WASM_EH, includeSymbolRenames: false);

    GnNinja("wasm-symgen", "third_party/freetype2:freetype2", args);
    GnNinja("wasm-symgen", "third_party/libjpeg-turbo:libjpeg", args);
    GnNinja("wasm-symgen", "third_party/libpng:libpng", args);

    var symgenOut = SKIA_PATH.Combine("out/wasm-symgen");

    // Anchors are real functions (not macros) that are unique to each library, used to find its
    // archive without assuming what GN names the output file for a given target.
    var freetypeArchive = FindArchiveContaining(symgenOut, "FT_Init_FreeType");
    var libjpegArchive = FindArchiveContaining(symgenOut, "jpeg_CreateDecompress");
    var libpngArchive = FindArchiveContaining(symgenOut, "png_read_info");

    // Note: libpng does have its own built-in symbol-prefixing mechanism (PNG_PREFIX), but it is
    // deliberately not used here: it requires hand-authoring a separate pngprefix.h with the same
    // kind of mapping this script already generates. Renaming everything that is actually global
    // at link time (as discovered via nm) is more complete, and keeps all three libraries on one
    // uniform mechanism.
    var symbols = new SortedSet<string>();
    symbols.UnionWith(GetDefinedGlobalSymbols(freetypeArchive));
    symbols.UnionWith(GetDefinedGlobalSymbols(libjpegArchive));
    symbols.UnionWith(GetDefinedGlobalSymbols(libpngArchive));

    if (symbols.Count == 0)
        throw new Exception("No symbols were discovered for freetype2/libjpeg-turbo/libpng -- something is wrong with the discovery build.");

    var lines = new List<string> {
        "// Generated by the 'generate-wasm-symbol-renames' cake target. DO NOT EDIT BY HAND.",
        "// Renames every global symbol freetype2/libjpeg-turbo/libpng would otherwise export,",
        "// so this static library cannot collide with a host application's own copies of the same",
        "// libraries (eg. Unity's bundled libfreetype2/libjpeg/libpng) when both get statically",
        "// linked together. Regenerated automatically on every build with --wasmRenameThirdPartySymbols",
        "// enabled -- do not rely on the copy checked into source control being current.",
        "#ifndef SKIASHARP_WASM_SYMBOL_RENAMES_H",
        "#define SKIASHARP_WASM_SYMBOL_RENAMES_H",
    };
    foreach (var symbol in symbols)
        lines.Add($"#define {symbol} {SYMBOL_RENAME_PREFIX}{symbol}");
    lines.Add("#endif");

    EnsureDirectoryExists(SYMBOL_RENAMES_HEADER.GetDirectory());
    System.IO.File.WriteAllLines(SYMBOL_RENAMES_HEADER.FullPath, lines);

    Information($"Wrote {symbols.Count} symbol renames to '{SYMBOL_RENAMES_HEADER}'.");
});

Task("libSkiaSharp")
    .IsDependentOn("git-sync-deps")
    .IsDependentOn("generate-wasm-symbol-renames")
    .WithCriteria(IsRunningOnLinux())
    .Does(() =>
{
    var emscriptenFeaturesModifiers =
        EMSCRIPTEN_FEATURES
        .Where(f => !f.StartsWith("_"))
        .ToArray();

    GnNinja($"wasm", "SkiaSharp", WasmSkiaGnArgs(HAS_SIMD_ENABLED, HAS_THREADING_ENABLED, HAS_WASM_EH, includeSymbolRenames: ENABLE_SYMBOL_RENAMES));

    var a = SKIA_PATH.CombineWithFilePath($"out/wasm/libSkiaSharp.a");

    // separate all the .a files into .o files
    var skiaOut = SKIA_PATH.Combine("out/wasm");
    var mergeDir = skiaOut.Combine("obj/merge");
    EnsureDirectoryExists(mergeDir);
    CleanDirectories(mergeDir.FullPath);
    foreach (var file in GetFiles($"{skiaOut}/*.a")) {
        RunProcess(AR, new ProcessSettings {
            Arguments = $"x \"{file}\"",
            WorkingDirectory = mergeDir.FullPath,
        });
    }

    // add the default font
    var input = SKIA_PATH.CombineWithFilePath("modules/canvaskit/fonts/NotoMono-Regular.ttf");
    var embed_resources = SKIA_PATH.CombineWithFilePath("tools/embed_resources.py");
    RunProcess(PYTHON_EXE, new ProcessSettings {
        Arguments = $"{embed_resources} --name SK_EMBEDDED_FONTS --input {input} --output {input}.cpp --align 4",
        WorkingDirectory = SKIA_PATH.FullPath,
    });
    RunProcess(CC, $"-std=c++17 -I. {input}.cpp -r -o {mergeDir}/NotoMonoRegularttf.o");

    // merge all the .o files into the final .a file
    var oFiles = GetFiles($"{mergeDir}/*.o");
    RunProcess(AR, $"-crs {a} {string.Join(" ", oFiles)}");

    var outDir = OUTPUT_PATH.Combine($"wasm");
    if (!string.IsNullOrEmpty(EMSCRIPTEN_VERSION))
        outDir = outDir.Combine("libSkiaSharp.a").Combine(EMSCRIPTEN_VERSION);
    if (emscriptenFeaturesModifiers.Length != 0)
        outDir = outDir.Combine(string.Join(",", emscriptenFeaturesModifiers));
    EnsureDirectoryExists(outDir);
    CopyFileToDirectory(a, outDir);
});

// Builds the real 'HarfBuzzSharp' target (harfbuzz-subset.cc amalgamates almost the entire
// harfbuzz source into it directly -- there's no separate third_party/harfbuzz dependency) into a
// dedicated out dir with internals hidden, then discovers its public API the same way
// 'generate-wasm-symbol-renames' does for the four C libraries. See documentation/wasm-symbol-renaming.md.
Task("generate-wasm-harfbuzz-symbol-renames")
    .IsDependentOn("git-sync-deps")
    .WithCriteria(IsRunningOnLinux() && ENABLE_SYMBOL_RENAMES)
    .Does(() =>
{
    var args = HarfBuzzSharpGnArgs(HAS_SIMD_ENABLED, HAS_THREADING_ENABLED, HAS_WASM_EH, hideInternalSymbols: true, includeGeneratedRenames: false);

    GnNinja("wasm-symgen-harfbuzz", "HarfBuzzSharp", args);

    var archive = SKIA_PATH.CombineWithFilePath("out/wasm-symgen-harfbuzz/libHarfBuzzSharp.a");
    var symbols = new SortedSet<string>(GetDefinedGlobalSymbols(archive));

    if (symbols.Count == 0)
        throw new Exception("No symbols were discovered for harfbuzz -- something is wrong with the discovery build.");

    // See GetHarfBuzzMacroShadowedNames -- these can't be renamed by textual substitution, so
    // leave them out of the rename table; both sides then agree on the real name.
    var macroShadowedNames = GetHarfBuzzMacroShadowedNames();
    var renamedSymbols = new SortedSet<string>(symbols.Except(macroShadowedNames));
    var unrenameable = new SortedSet<string>(symbols.Intersect(macroShadowedNames));
    if (unrenameable.Count > 0)
        Warning($"{unrenameable.Count} harfbuzz function(s) can't be renamed (shadowed by harfbuzz's own inline macro at their definition site) and will keep their original name, unlike the rest of harfbuzz's public API: {string.Join(", ", unrenameable)}");

    // The managed binding P/Invokes these hb_* names directly, so 'wasm_symbol_aliases.h'
    // re-exports each renamed one under its original name (see HarfBuzzSharpGnArgs). Names in
    // 'unrenameable' are skipped -- they were never renamed, so no alias is needed.
    var managedApiNames = GetHarfBuzzManagedApiNames();
    var aliasNames = new SortedSet<string>(managedApiNames.Where(n => renamedSymbols.Contains(n)));

    var missing = managedApiNames.Where(n => !symbols.Contains(n)).ToList();
    if (missing.Count > 0)
        Warning($"{missing.Count} harfbuzz function(s) referenced by the managed HarfBuzzSharp binding were not found in this build's public API (eg. disabled by a feature define) and will not be renamed/aliased: {string.Join(", ", missing)}");

    var renameLines = new List<string> {
        "// Generated by the 'generate-wasm-harfbuzz-symbol-renames' cake target. DO NOT EDIT BY HAND.",
        "// Renames every global symbol harfbuzz's public API exports, to avoid colliding with a",
        "// host application's own bundled harfbuzz. See documentation/wasm-symbol-renaming.md.",
        "// Regenerated on every build with --wasmRenameThirdPartySymbols enabled.",
        "#ifndef SKIASHARP_WASM_HARFBUZZ_SYMBOL_RENAMES_H",
        "#define SKIASHARP_WASM_HARFBUZZ_SYMBOL_RENAMES_H",
    };
    foreach (var symbol in renamedSymbols)
        renameLines.Add($"#define {symbol} {SYMBOL_RENAME_PREFIX}{symbol}");
    renameLines.Add("#endif");

    EnsureDirectoryExists(HARFBUZZ_SYMBOL_RENAMES_HEADER.GetDirectory());
    System.IO.File.WriteAllLines(HARFBUZZ_SYMBOL_RENAMES_HEADER.FullPath, renameLines);

    var aliasLines = new List<string> {
        "// Generated by the 'generate-wasm-harfbuzz-symbol-renames' cake target. DO NOT EDIT BY HAND.",
        "// Re-exports each renamed harfbuzz function the managed HarfBuzzSharp binding P/Invokes,",
        "// under its original name. See documentation/wasm-symbol-renaming.md.",
        "#ifndef SKIASHARP_WASM_HARFBUZZ_SYMBOL_ALIASES_H",
        "#define SKIASHARP_WASM_HARFBUZZ_SYMBOL_ALIASES_H",
    };
    foreach (var symbol in aliasNames)
        aliasLines.Add($"extern __attribute__((visibility(\"default\"))) void {symbol}(void) __attribute__((alias(\"{SYMBOL_RENAME_PREFIX}{symbol}\")));");
    aliasLines.Add("#endif");

    EnsureDirectoryExists(HARFBUZZ_SYMBOL_ALIASES_HEADER.GetDirectory());
    System.IO.File.WriteAllLines(HARFBUZZ_SYMBOL_ALIASES_HEADER.FullPath, aliasLines);

    Information($"Wrote {renamedSymbols.Count} harfbuzz symbol renames ({unrenameable.Count} left un-renamed) to '{HARFBUZZ_SYMBOL_RENAMES_HEADER}' and {aliasNames.Count} aliases to '{HARFBUZZ_SYMBOL_ALIASES_HEADER}'.");
});

Task("libHarfBuzzSharp")
    .IsDependentOn("generate-wasm-harfbuzz-symbol-renames")
    .WithCriteria(IsRunningOnLinux())
    .Does(() =>
{
    var emscriptenFeaturesModifiers =
        EMSCRIPTEN_FEATURES
        .Where(f => !f.StartsWith("_"))
        .ToArray();

    // The alias declarations (see 'generate-wasm-harfbuzz-symbol-renames') are force-included
    // directly into this same GN/ninja build via HarfBuzzSharpGnArgs -- no separate compile/merge
    // step needed; __attribute__((alias(...))) requires same-translation-unit resolution, which
    // is exactly what force-including achieves.
    GnNinja($"wasm", "HarfBuzzSharp", HarfBuzzSharpGnArgs(HAS_SIMD_ENABLED, HAS_THREADING_ENABLED, HAS_WASM_EH, hideInternalSymbols: ENABLE_SYMBOL_RENAMES, includeGeneratedRenames: ENABLE_SYMBOL_RENAMES));

    var so = SKIA_PATH.CombineWithFilePath($"out/wasm/libHarfBuzzSharp.a");

    var outDir = OUTPUT_PATH.Combine($"wasm");
    if (!string.IsNullOrEmpty(EMSCRIPTEN_VERSION))
        outDir = outDir.Combine("libHarfBuzzSharp.a").Combine(EMSCRIPTEN_VERSION);
    if (emscriptenFeaturesModifiers.Length != 0)
        outDir = outDir.Combine(string.Join(",", emscriptenFeaturesModifiers));
    EnsureDirectoryExists(outDir);
    CopyFileToDirectory(so, outDir);
    CopyFile(so, outDir.CombineWithFilePath("libHarfBuzzSharp.a"));
});

Task("Default")
    .IsDependentOn("libSkiaSharp")
    .IsDependentOn("libHarfBuzzSharp");

RunTarget(TARGET);
